### ISSUE TITLE
Pack extension fails when running on Windows

### ISSUE THREAD

**Issue by macsux** [tilt-dev/tilt-extensions#294]
Pack extension fails when tilt is run on Windows with `Error parsing reference: "$EXPECTED_REF" is not a valid repository/tag: invalid reference format: repository name must be lowercase`. Same tiltfile works fine when run under WSL (Ubuntu).

Tiltfile:
```python
allow_k8s_contexts('gke_fe-astakhov_us-central1-c_gke-play')

load('ext://pack', 'pack')

pack('macsux/dotnet-accelerator', 
    env_vars=['BP_LIVE_RELOAD_ENABLED=true', 'BP_DOTNET_PROJECT_PATH=./src/MyProjectGroup.DotnetAccelerator'])

k8s_yaml(['kubernetes/deployment.yaml'])
k8s_resource('dotnet-accelerator', port_forwards=8080)
```

**Comment by hyu** [comment]
Hi @macsux, thanks for your report. 

Have you been able to come up with an equivalent command that you can get to work in Windows?

It seems that the issue is that we need a separate command_bat [here](https://github.com/tilt-dev/tilt-extensions/blob/master/pack/Tiltfile#L53)

Windows' cmd uses `%EXPECTED_REF%` instead of $EXPECTED_REF

which, if that were the only issue, would be simple enough. but I think also the && won't work
oh I guess `&&` work in bash, so maybe it's just a matter of swapping $ for %%


or we could take a stab at a command and ask them to try it

I've also been tempted to add a CI check to the extensions repo to make sure all extensions either specify command_bats or opt out of windows support

**Comment by hyu** [comment]
Hi @macsux, thanks for your report. 

Have you been able to come up with an equivalent command that you can get to work in Windows?

It seems that the issue is that we need a separate command_bat [here](https://github.com/tilt-dev/tilt-extensions/blob/master/pack/Tiltfile#L53)

Windows' cmd uses `%EXPECTED_REF%` instead of $EXPECTED_REF

Which, if that were the only issue, would be simple enough. but I think also the && won't work
 `&&` work in bash, so maybe it's just a matter of swapping $ for %%


or we could take a stab at a command and ask them to try it

I've also been tempted to add a CI check to the extensions repo to make sure all extensions either specify command_bats or opt out of windows support

**Comment by macsux** [comment]
See the [example Tiltfile](https://github.com/macsux/dotnet-accelerator/blob/dev/Tiltfile) I made that does this properly on both windows & linux. The same approach can be applied inside the extension.
